[project]
name = "brain2text"
version = "0.1.0"
description = "I can read your mind!!!"
readme = "README.md"
requires-python = ">=3.10"
dependencies = []

[dependency-groups]
dev = [
    "icecream>=2.1.3",
]
